[sqlDb]
db_url="host=postgres user=postgres password=guessme dbname=messages-db sslmode=disable"

max_idle_connections=5
max_open_connections=15

aquire_connection_timeout_seconds=3

current_version=1

[common]
log_level = "Debug"